name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - name: Test report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: Unit Tests            
          path: ./junit.xml    
          reporter: jest-junit 
